name: Variables
on: [push]

env:
  NIVEAU_WORKFLOW: "Je suis une variable de workflow"

jobs:
  mon_job:
    runs-on: ubuntu-latest
    env:
      NIVEAU_JOB: "Je suis une variable de job"
    steps:
      - name: Étape 1
        env:
          NIVEAU_JOB: echo ${{ env.NIVEAU_JOB }}
          NIVEAU_ETAPE: "Je suis une variable d'étape"
          
        run: |
          echo "$NIVEAU_WORKFLOW"
          echo "$NIVEAU_JOB"
          echo "$NIVEAU_ETAPE"
