name: Exemple de dépendances entre steps
on: [push]

jobs :
  premier_job :
    runs-on : ubuntu-latest
    steps :
      - name : Je suis étape 1
        id : etape1
        run : echo "output_var1=pomme" >> $GITHUB_OUTPUT
      - name : Je suis étape 2
        id : etape2
        run : echo steps.etape1.ouputs.output_var1 should be poire
        if: steps.etape1.ouputs.output_var1 != poire
    

