name: Exemple de dépendances entre jobs

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Tâche de job1
      run: echo "Exécution de job1" && sleep 5

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: Tâche de job2
      run: echo "Exécution de job2 après job1" && sleep 5

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
    - name: Tâche de job3
      run: echo "Exécution de job3 après job1 et job2"
