name: nombre maximal de travaux parallèles

on: push

jobs:
  example_matrix:
    strategy:
      max-parallel: 2
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Résumé de l'exemple job avec Matrix
      run: |
        echo "Pour chaque combinaison de la matrix OS/Version:" >> $GITHUB_STEP_SUMAMRY
        echo "1. Affichache de l'OS" >> $GITHUB_STEP_SUMAMRY
        echo "2. Version de l'OS" >> $GITHUB_STEP_SUMAMRY
        echo "3. Puis pause de 5 secondes entre chaque job " >> $GITHUB_STEP_SUMAMRY
        
    - run: echo "os est ${{ matrix.os }}"
    - run: echo "version est ${{ matrix.version }}"
    - run: sleep 5

    
      