name: Exemple de build d'un projet Vite
on: [push]

defaults:
  run:
    working-directory: ./vite-project

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v4

      - name: Fetch directory
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install


