name: nombre maximal de travaux parallèles

on: push

jobs:
  example_matrix:
    strategy:
      max-parallel: 2
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - run: echo "os est ${{ matrix.os }}"
    - run: echo "version est ${{ matrix.version }}"
    - run: sleep 5