name: Exemple de dépendances entre jobs
on: [push]

jobs :
  exemple :
    runs-on : ubuntu-latest
    steps :
      - name : définir une variable
        run : echo "MA_VARIABLE=Bonjour" >> $GITHUB_ENV
      - name : utiliser la variable
        run : echo "La valeur de MA_VARIABLE est $MA_VARIABLE."
