name: Exemple de notification d'erreur
on: [push]

jobs:
  exemple_error:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher un message d'erreur
        run: echo "::error file=exemple.txt,line=1,col=5::Un message d'erreur"

